name: dreamflow
description: "A DreamFlow project"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  file_picker: '>=8.1.2'
  cached_network_image: ^3.0.0
  permission_handler: ^12.0.0
  audioplayers: ^6.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  fl_chart: 0.68.0
  google_fonts: 6.1.0
  shared_preferences: 2.3.2
  path_provider: ^2.1.0
  provider: 6.1.2
  http: '>=1.0.0'
  uuid: '>=3.0.0'
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true
